eight_points_guzzle:
    clients:
        webhook_client:
            options:
                timeout: 5

                # Configure headers.
                # More info: http://docs.guzzlephp.org/en/stable/request-options.html#headers
                headers:
                    User-Agent: "Postmill/0.6 (https://postmill.xyz/)"
                    Accept: application/json, */*
                    Content-Type: application/json

            # Find plugins here:
            # https://github.com/8p/EightPointsGuzzleBundle#known-and-supported-plugins
            plugin: ~

        submission_image_client:
            options:
                timeout: 10
                headers:
                    User-Agent: "Postmill/0.6 (https://postmill.xyz/)"
                    Accept: image/png, image/jpeg, image/gif
