image: php:7.1

cache:
    paths:
        - vendor/

before_script:
    - apt-get update -yqq
    - apt-get install -yqq git libmcrypt-dev libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev
    - docker-php-ext-install mbstring mcrypt pdo_pgsql curl json intl gd xml zip bz2 opcache
    - pecl install apcu
    - docker-php-ext-enable apcu
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install -n
    - bin/console doctrine:migrations:migrate -nq
    - bin/console doctrine:fixtures:load -n

services:
    - postgres:9.6-alpine

variables:
    POSTGRES_USER: postmill
    POSTGRES_PASSWORD: ""
    DATABASE_URL: "pgsql://postmill@postgres/postmill?serverVersion=9.6"

test:
    script:
        - bin/phpunit --coverage-text --colors=never
