request_password_reset:
    controller: App\Controller\ResetPasswordController::requestReset
    path: /reset_password
    methods: [GET, POST]

password_reset:
    controller: App\Controller\ResetPasswordController::reset
    path: /reset_password/{id}/{expires}/{checksum}
    methods: [GET, POST]
    requirements: { id: \d+, expires: \d+, checksum: '[0-9a-f]+' }
