# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    days_to_keep_logs: 7
    user_forum_creation_interval: 1 day
    uuid_regex:      '[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}'
    wiki_page_regex: '[A-Za-z][A-Za-z0-9_-]*(/[A-Za-z][A-Za-z0-9_-]*)*'
    env(APP_ENABLE_WEBHOOKS): false

services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    _instanceof:
        Doctrine\Common\EventSubscriber:
            tags: ['doctrine.event_subscriber']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../src/{Entity,Migrations}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    App\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']

    App\Command\ActivateMaintenanceMode:
        arguments:
            $siteName: "%env(SITE_NAME)%"
            $includeFilePath: "%kernel.project_dir%/var/maintenance.php"

    App\Command\AddUserCommand:
        arguments:
            $defaultLocale: "%env(APP_LOCALE)%"

    App\Controller\ForumController:
        arguments:
            $enableWebhooks: "%env(bool:APP_ENABLE_WEBHOOKS)%"

    App\Controller\UserController:
        arguments:
            $defaultLocale: "%env(APP_LOCALE)%"

    App\EventListener\AjaxListener:
        arguments:
            $serializer: "@serializer"

    App\EventListener\LocaleListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 15 }
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }

    App\EventListener\SubmissionImageListener:
        arguments:
            $filesystem: "@oneup_flysystem.submission_images_filesystem"
        public: true
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: kernel.event_listener, event: kernel.terminate }

    App\EventListener\WebhookListener:
        arguments:
            $client: "@eight_points_guzzle.client.webhook_client"
            $webhooksEnabled: "%env(bool:APP_ENABLE_WEBHOOKS)%"

    App\Form\RequestPasswordResetType:
        arguments:
            $bypass: "@=parameter('kernel.environment') === 'test'"

    App\Mailer\ResetPasswordMailer:
        arguments:
            $siteName: "%env(SITE_NAME)%"
            $noReplyAddress: "%env(NO_REPLY_ADDRESS)%"
            $salt: "%env(APP_SECRET)%"

    App\Security\Voter\TokenVoter:
        arguments:
            $forumCreationInterval: "%user_forum_creation_interval%"

    App\Twig\AppExtension:
        arguments:
            $siteName: "%env(SITE_NAME)%"
            $enableWebhooks: "%env(bool:APP_ENABLE_WEBHOOKS)%"

    App\Utils\CachedMarkdownConverter:
        arguments:
            $cacheItemPool: "@cache.markdown"

    App\Utils\AuthenticationHelper:
        arguments:
            $rememberMeServices: "@security.authentication.rememberme.services.simplehash.main"
            $secret: "%env(APP_SECRET)%"


    ## Misc

    Doctrine\DBAL\Connection: "@doctrine.dbal.default_connection"

    Doctrine\Common\Persistence\ObjectManager: "@doctrine.orm.entity_manager"
    Doctrine\ORM\EntityManager: "@doctrine.orm.entity_manager"
    Doctrine\ORM\EntityManagerInterface: "@doctrine.orm.default_entity_manager"

    Symfony\Bundle\SecurityBundle\Security\FirewallMap: "@security.firewall.map"
